package br.com.sga.entidade.enums;

public enum Tabela {
	AUDIENCIA,CLIENTE,CONSULTA,CONTRATO,DESPESAS,ENDERECO,FINANCEIRO,
	FUNCIONARIO,NOTIFICACAO,PARCELA,PARTE,PROCESSO,RECEITA,TELEFONE,
	TESTEMUNHA,VINCULO_FUNCIONARIO
}
